### ISSUE TITLE
Percentage Sleep

### ISSUE THREAD

**Issue by rainestormee** [CSSUoB/CSS-Minecraft#3]
Time set day if more than 50% of the server is sleeping.
+ Messages that say x/online players are sleeping, where you need a threshold of how many to sleep.

**Comment by Thatsmusic99** [comment]
With the new gamerule this is probably redundant unless we want to backport to older versions too?

**Comment by rainestormee** [comment]
Yeah we should close this now. No need to backport. We had some plans on running legacy modpacks but if there is a need that can be a fork of this.
